name: "Terraform CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-spec:
    name: "Lint, Format, and Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Check Formatting
        run: terraform fmt -check -recursive

      - name: Initialize and Validate Environment
        run: |
          cd terraform/environments
          terraform init -backend=false
          terraform validate